In [2]:
import numpy as np
from scipy.ndimage import binary_erosion

# Given 5x5 structuring element
selem = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0 0 0 0 0 0],
 [0 0 0 0 0 0 0 0 0 0 0],
 [0 0 0 0 0 0 0 0 0 0 0],
 [0 0 0 0 0 0 0 0 0 0 0],
 [0 0 0 0 0 0 0 0 0 0 0],
 [0 0 0 0 0 0 0 0 0 0 0],
 [0 0 0 0 0 0 0 0 0 0 0],
 [0 0 0 0 0 0 0 0 0 0 0],
 [0 0 0 0 0 0 0 0 0 0 0]])

# Create the 11x11 matrix
rows, cols = 11, 11
matrix = np.zeros((rows, cols), dtype=int)

# Perform binary erosion with the inverse of the structuring element on the matrix
inverse_selem = 1 - selem  # Inverse the structuring element
eroded_matrix = binary_erosion(matrix, structure=inverse_selem)

# Print the resulting eroded matrix
print(eroded_matrix)


SyntaxError: invalid syntax. Perhaps you forgot a comma? (2116616480.py, line 7)